#!/bin/bash
#PBS -m bea
#PBS -N {jobname}
#PBS -M {email}
#PBS -W group_list={group_list}
#PBS -q standard
#PBS -l jobtype=htc_only
#PBS -l select=1:ncpus=5:mem=23gb
#PBS -l cput=0:{cput}:0
#PBS -l walltime=0:{walltime}:0
cd /extra/{username}/ExoticHiggs/{mg5_process_dir}
for i in {{1..{nruns}}}
do
  ./bin/generate_events -f --laststep=delphes
  ./bin/madevent remove all parton -f
  ./bin/madevent remove all pythia -f
done
echo "DONE"
exit 0
